### ISSUE TITLE
peerflix cleans unnecessarily

### ISSUE THREAD

**Issue by smhmd** [noctuid/mpv-peerflix-hook#2]
I could play a local or youtube video and `peerflix-hook` would attempt to clean before quit.
```
$ mpv file.mkv
AO: [pulse] 48000Hz stereo 2ch float
VO: [gpu] 400x288 yuv420p
(Paused) AV: 00:00:00 / 00:30:03 (0%) A-V:  0.000
Saving state.
[peerflix] Removing peerflix video file

Exiting... (Quit)
$|
```

It also tries and fails to delete `/tmp/torrent-stream` created by vanilla `peerflix`. (I'm not too worried about this one since I don't run `peerflix` at all these days.)

point is that `peerflix-hook` runs unnecessarily, I think.

**Comment by noctuid** [comment]
Thanks, it should work correctly now.
